# Generated by Django 6.0.2 on 2026-02-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0002_add_data_source_and_visualizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedvisualization',
            name='chart_options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
