# Generated by Django 6.0.2 on 2026-02-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0003_add_chart_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedvisualization',
            name='sql',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='savedvisualization',
            name='table_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
