# Generated by Django 6.0.2 on 2026-02-13 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
        ('data_sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='data_sources.datasource'),
        ),
    ]
