# Generated by Django 6.0.2 on 2026-02-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_default_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=list, help_text="List of permission codes, e.g. ['reports.view', 'reports.edit', 'users.manage']"),
        ),
    ]
